2025-10-20 16:54:32,744 ERROR: Exception on / [GET] [in C:\Users\dima\microblog\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\dima\microblog\app\routes.py", line 29, in index
    posts = db.paginate(current_user.following_posts(), page=page, per_page=app.config['POSTS_PER_PAGE'], error_out=False)
                                                                            ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'POSTS_PER_PAGE'
2025-10-20 16:55:53,712 INFO: Microblog startup [in C:\Users\dima\microblog\app\__init__.py:45]
2025-10-20 16:56:06,888 INFO: Microblog startup [in C:\Users\dima\microblog\app\__init__.py:45]
2025-10-20 16:56:14,068 INFO: Microblog startup [in C:\Users\dima\microblog\app\__init__.py:45]
2025-10-20 16:56:42,026 ERROR: Exception on / [GET] [in C:\Users\dima\microblog\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\dima\microblog\app\routes.py", line 29, in index
    posts = db.paginate(current_user.following_posts(), page=page, per_page=app.config['POSTS_PER_PAGE'], error_out=False)
                                                                            ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'POSTS_PER_PAGE'
2025-10-20 16:56:52,811 ERROR: Exception on /index [GET] [in C:\Users\dima\microblog\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\dima\microblog\app\routes.py", line 29, in index
    posts = db.paginate(current_user.following_posts(), page=page, per_page=app.config['POSTS_PER_PAGE'], error_out=False)
                                                                            ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'POSTS_PER_PAGE'
2025-10-20 17:02:30,720 INFO: Microblog startup [in C:\Users\dima\microblog\app\__init__.py:45]
2025-10-20 17:02:36,021 ERROR: Exception on /index [GET] [in C:\Users\dima\microblog\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\dima\microblog\app\routes.py", line 29, in index
    posts = db.paginate(current_user.following_posts(), page=page, per_page=app.config['SECRET_KEY'], error_out=False)
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask_sqlalchemy\extension.py", line 839, in paginate
    return SelectPagination(
        select=select,
    ...<5 lines>...
        count=count,
    )
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask_sqlalchemy\pagination.py", line 56, in __init__
    page, per_page = self._prepare_page_args(
                     ~~~~~~~~~~~~~~~~~~~~~~~^
        page=page,
        ^^^^^^^^^^
    ...<2 lines>...
        error_out=error_out,
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask_sqlalchemy\pagination.py", line 132, in _prepare_page_args
    if per_page < 1:
       ^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'str' and 'int'
2025-10-20 17:02:40,709 ERROR: Exception on /index [GET] [in C:\Users\dima\microblog\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\dima\microblog\app\routes.py", line 29, in index
    posts = db.paginate(current_user.following_posts(), page=page, per_page=app.config['SECRET_KEY'], error_out=False)
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask_sqlalchemy\extension.py", line 839, in paginate
    return SelectPagination(
        select=select,
    ...<5 lines>...
        count=count,
    )
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask_sqlalchemy\pagination.py", line 56, in __init__
    page, per_page = self._prepare_page_args(
                     ~~~~~~~~~~~~~~~~~~~~~~~^
        page=page,
        ^^^^^^^^^^
    ...<2 lines>...
        error_out=error_out,
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dima\microblog\venv\Lib\site-packages\flask_sqlalchemy\pagination.py", line 132, in _prepare_page_args
    if per_page < 1:
       ^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'str' and 'int'
